name: 'Setup test environment'
description: 'Setup test environment'
outputs:
  Error:
    description: "Error writing file to disk"
  "ModifiedChart":
    description: "Modified chart js"
  "ModifiedIndex":
    description: "Modified index js"
runs:
  using: 'node20'
  main: '../dist/TestSetupAction/index.js'
