name: 'Test coverage'
on:
  workflow_dispatch:

jobs:
  test_env_setup_job:
    runs-on: ubuntu-latest
    name: A job to setup test environment

    steps:
      - name: Checkout [react-charting]
        uses: actions/checkout@v3
        with: 
          repository: "microsoft/fluentui"
          path: "packages/react-charting"
          
      - name: Run coverage report
        working-directory: microsoft/fluentui/packages/react-charting
        run: yarn jest --coverage --collectCoverageFrom='./src/*'
        
