name: 'Setup test environment'
on:
  workflow_dispatch:
jobs:
  test_env_setup_job:
    runs-on: ubuntu-latest
    name: A job to setup test environment
    steps:
      - name: Checkout [master]
        uses: actions/checkout@v3

      - name: Install packages
        run: yarn --cwd ./tools/UnitTestApp --verbose

      - name: Test Environment Setup action step
        uses: ./tools/UnitTestApp/TestSetup
